services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=markets_weekly
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
