"""Initial migration

Revision ID: 9ee56fa29f3d
Revises: 
Create Date: 2025-07-20 09:44:40.846033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee56fa29f3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('m1', sa.Float(), nullable=True),
    sa.Column('m3', sa.Float(), nullable=True),
    sa.Column('m6', sa.Float(), nullable=True),
    sa.Column('m12', sa.Float(), nullable=True),
    sa.Column('ytd', sa.Float(), nullable=True),
    sa.Column('qtd', sa.Float(), nullable=True),
    sa.Column('week', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit', sa.String(), nullable=False),
    sa.Column('qas_bp', sa.Float(), nullable=True),
    sa.Column('m1', sa.Float(), nullable=True),
    sa.Column('m3', sa.Float(), nullable=True),
    sa.Column('m6', sa.Float(), nullable=True),
    sa.Column('m12', sa.Float(), nullable=True),
    sa.Column('ytd', sa.Float(), nullable=True),
    sa.Column('qtd', sa.Float(), nullable=True),
    sa.Column('week', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equity', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('m1', sa.Float(), nullable=True),
    sa.Column('m3', sa.Float(), nullable=True),
    sa.Column('m6', sa.Float(), nullable=True),
    sa.Column('m12', sa.Float(), nullable=True),
    sa.Column('ytd', sa.Float(), nullable=True),
    sa.Column('qtd', sa.Float(), nullable=True),
    sa.Column('week', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_rate', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('m1', sa.Float(), nullable=True),
    sa.Column('m3', sa.Float(), nullable=True),
    sa.Column('m6', sa.Float(), nullable=True),
    sa.Column('m12', sa.Float(), nullable=True),
    sa.Column('ytd', sa.Float(), nullable=True),
    sa.Column('qtd', sa.Float(), nullable=True),
    sa.Column('week', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('major_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('indicator_event', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('unicredit_estimates', sa.Float(), nullable=True),
    sa.Column('consensus_bloomberg', sa.Float(), nullable=True),
    sa.Column('previous', sa.Float(), nullable=True),
    sa.Column('week', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate', sa.String(), nullable=False),
    sa.Column('yield_percent', sa.Float(), nullable=True),
    sa.Column('m1', sa.Float(), nullable=True),
    sa.Column('m3', sa.Float(), nullable=True),
    sa.Column('m6', sa.Float(), nullable=True),
    sa.Column('m12', sa.Float(), nullable=True),
    sa.Column('ytd', sa.Float(), nullable=True),
    sa.Column('qtd', sa.Float(), nullable=True),
    sa.Column('week', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    op.drop_table('major_events')
    op.drop_table('exchange_rates')
    op.drop_table('equities')
    op.drop_table('credit')
    op.drop_table('commodities')
    # ### end Alembic commands ###
